### PR TITLE
Add minimal CentOS support

### PR DESCRIPTION
**Pull request by vitkhab**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

* Added new task to install dependencies in RedHat OS family
* Added usage info in `README.md` 

### Benefits

User can install bitbucket on CentOS or RHEL using asible role.

### Possible Drawbacks

There is no drawback I would know about

### Applicable Issues

RHEL and CentOS repositories have old version of git. User must use one of workarounds written in Readme.

### CODE REVIEW

**Comment by jnogol** [comment]
Hi @vitkhab,

I tried to make it work with Centos and made it work, but was a bit PITA. Maybe is because of my lack of expertise with Centos, but could you please provide an example and edit the tests so Molecule could check if the role works in Centos as well? And please, add your contribution to the changelog.

Again, thanks for your work.

**Comment by vitkhab** [comment]
Would it be okay, to use prebuilt docker image with git version 2.2.0+?
CentOS have old version of git in official repos not compatible with Bitbucket. I wrote down the guide how to install newer version in Readme.md in this PR.

Sorry for long silence. I'm interested in merging this PR, but I had little time for that.

**Comment by jnogol** [comment]
Hi @vitkhab,

No problem at all. Regarding the use of a custom Docker image for the test, feel free :)

**Comment by vitkhab** [comment]
I've been using geerlingguy.java in my setup and it all works with CentOS. I've found out tests are using idealista.java-role role which lacks CentOS support.

I think I have to add CentOS support to idealista.java-role first. Then it will be possible for me to complete this PR. It's okay but it will take some time.

**Comment by syeda001** [comment]
Hi @vitkhab
the playbook execution is green. but when i have checked in node(i.e centos7), Bitbucket service is failed . i tried to install the dependencies also like git version >= 2.11, and java1.8. but still service is failed could you please update your branch with the successful code, as i found this playbook to be simpler and easy to understand.
quick response will be appreciated. thanks

**Comment by vitkhab** [comment]
Hi @syeda001. 
> the playbook execution is green. but when i have checked in node(i.e centos7), Bitbucket service is failed . i tried to install the dependencies also like git version >= 2.11, and java1.8. but still service is failed could you please update your branch with the successful code, as i found this playbook to be simpler and easy to understand.

What do you see if you try to access Bitbucket? Do you see anything strange in logs?

I checked my configuration and I see that I use `geerlingguy.java` role for installing Java on my Bitbucket Server. CentOS stores Java on different path than Debian, so I've changed configuration:
```yaml
bitbucket_java_home: "/usr/lib/jvm/jre/"
```

> quick response will be appreciated. thanks

Sorry for late answer.

**Comment by vitkhab** [comment]
I've added my configuration for testing role in CentOS Docker container. Most for example of usage.

Role seems outdated. Molecule, Ansible and even Python use in tests are not supported anymore. And there was no update for last two years. I have no intention to update this PR further.

**Comment by ablancolopez** [comment]
Closing, as OP has no intention to further develop this PR. Feel free to reopen if you change your mind :) thanks!

**Pull request closed without merging**
